[build]
  publish = "public"
  functions = "netlify/functions"

# ===== MEMBERS: tylko active/admin =====
[[redirects]]
  from = "/members/*"
  to = "/members/:splat"
  status = 200
  force = true
  conditions = { Role = ["active", "admin"] }

[[redirects]]
  from = "/members/*"
  to = "/unauthorized.html"
  status = 401
  force = true

# ===== DASHBOARD: tylko zalogowani (pending/active/admin) =====
[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200
  force = true
  conditions = { Role = ["pending", "active", "admin"] }

[[redirects]]
  from = "/dashboard.html"
  to = "/"
  status = 302
  force = true

# HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Bez cache dla members
[[headers]]
  for = "/members/*"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"

# Nie buforuj dashboardu - wymusza pełne odświeżenie po powrocie
[[headers]]
  for = "/dashboard.html"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"

# (Już masz) bez cache dla members
[[headers]]
  for = "/members/*"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"
# Kanoniczny adres dashboardu to /dashboard.html
[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 301
  force = true

[[redirects]]
  from = "/dashboard/"
  to = "/dashboard.html"
  status = 301
  force = true
