[build]
  publish = "public"
  functions = "netlify/functions"

# ===== MEMBERS: tylko active/admin =====
# 1) Wpuść, gdy jest rola (wymaga nf_jwt)
[[redirects]]
  from = "/members/*"
  to = "/members/:splat"
  status = 200
  force = true
  conditions = { Role = ["active", "admin"] }

# 2) Fallback: brak roli/ciasteczka -> 401/Unauthorized (albo daj 302 na "/")
[[redirects]]
  from = "/members/*"
  to = "/unauthorized.html"
  status = 401
  force = true

# ===== DASHBOARD: tylko zalogowani (pending/active/admin) =====
# 1) Wpuść zalogowanych
[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200
  force = true
  conditions = { Role = ["pending", "active", "admin"] }

# 2) Fallback: niezalogowany -> 302 na stronę startową lub 401/unauthorized
[[redirects]]
  from = "/dashboard.html"
  to = "/"
  status = 302
  force = true

# HTTPS (zostaw jak miałeś)
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Cache: nie buforuj members (przeglądarka + CDN)
[[headers]]
  for = "/members/*"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"
