[build]
  publish   = "public"
  functions = "netlify/functions"

# --- API NA GÓRZE ---
[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/chat"
  status = 200
  force  = true

# --- HTTPS ---
[[redirects]]
  from = "http://*"
  to   = "https://:splat"
  status = 301
  force  = true

# --- LOGIN: publiczny obszar (SPA-friendly) ---
[[redirects]]
  from = "/login/*"
  to   = "/login/:splat"
  status = 200
  force  = true

# --- MEMBERS: tylko active/admin ---
[[redirects]]
  from = "/members/*"
  to   = "/members/:splat"
  status = 200
  force  = true
  conditions = { Role = ["active", "admin"] }

[[redirects]]
  from = "/members/*"
  to   = "/unauthorized.html"
  status = 401
  force  = true

# --- DASHBOARD: pending/active/admin ---
[[redirects]]
  from = "/dashboard.html"
  to   = "/dashboard.html"
  status = 200
  force  = true
  conditions = { Role = ["pending", "active", "admin"] }

# Niezalogowanych kierujemy na /login/ (unikamy /)
[[redirects]]
  from = "/dashboard.html"
  to   = "/login/?from=/dashboard.html"
  status = 302
  force  = true

# Kanoniczny adres dashboardu
[[redirects]]
  from = "/dashboard"
  to   = "/dashboard.html"
  status = 301
  force  = true

[[redirects]]
  from = "/dashboard/"
  to   = "/dashboard.html"
  status = 301
  force  = true

# --- Nagłówki ---
[[headers]]
  for = "/members/*"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"

[[headers]]
  for = "/dashboard.html"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"

[[headers]]
  for = "/members/modules/yt/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.youtube.com https://s.ytimg.com; frame-src https://www.youtube-nocookie.com https://www.youtube.com; connect-src 'self' https://www.youtube.com https://www.youtube-nocookie.com; img-src 'self' https://i.ytimg.com data:; style-src 'self' 'unsafe-inline'; media-src https://*.googlevideo.com"

[dev]
  publish   = "public"
  functions = "netlify/functions"
