[build]
  publish = "public"
  functions = "netlify/functions"

# MEMBERS – tylko dla active/admin (wymaga ciasteczka nf_jwt)
[[redirects]]
  from = "/members/*"
  to = "/members/:splat"
  status = 200
  force = true
  conditions = { Role = ["active", "admin"] }

# Fallback: jeśli brak roli → na stronę startową (lub dashboard, jak wolisz)
[[redirects]]
  from = "/members/*"
  to = "/"
  status = 302

# DASHBOARD – tylko zalogowani (pending/active/admin)
[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200
  force = true
  conditions = { Role = ["pending", "active", "admin"] }

[[redirects]]
  from = "/dashboard.html"
  to = "/"
  status = 302

# HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Anty-cache dla members (żeby przeglądarka nie trzymała w incognito zasobów)
[[headers]]
  for = "/members/*"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"
