[build]
  publish   = "public"
  functions = "netlify/functions"

# --- API (musi być wysoko, przed catch-all) ---
[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/chat"
  status = 200
  force  = true

# --- HTTPS wymuszenie ---
[[redirects]]
  from = "http://*"
  to   = "https://:splat"
  status = 301
  force  = true

# --- MEMBERS: tylko active/admin ---
[[redirects]]
  from = "/members/*"
  to   = "/members/:splat"
  status = 200
  force  = true
  conditions = { Role = ["active", "admin"] }

[[redirects]]
  from = "/members/*"
  to   = "/unauthorized.html"
  status = 401
  force  = true

# --- DASHBOARD: pending/active/admin ---
[[redirects]]
  from = "/dashboard.html"
  to   = "/dashboard.html"
  status = 200
  force  = true
  conditions = { Role = ["pending", "active", "admin"] }

[[redirects]]
  from = "/dashboard.html"
  to   = "/"
  status = 302
  force  = true

# Kanoniczny adres dashboardu
[[redirects]]
  from = "/dashboard"
  to   = "/dashboard.html"
  status = 301
  force  = true

[[redirects]]
  from = "/dashboard/"
  to   = "/dashboard.html"
  status = 301
  force  = true

# --- Nagłówki: bez cache dla members i dashboardu ---
[[headers]]
  for = "/members/*"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"

[[headers]]
  for = "/dashboard.html"
  [headers.values]
    Cache-Control = "private, no-store, no-cache, must-revalidate"

# --- Fallback 404 (MUSI BYĆ NA KOŃCU) ---
[[redirects]]
  from = "/*"
  to   = "/unauthorized.html"
  status = 404

# (opcjonalnie ułatwia lokalne `netlify dev`)
[dev]
  publish   = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/members/modules/yt/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.youtube.com https://s.ytimg.com; frame-src https://www.youtube-nocookie.com https://www.youtube.com; connect-src 'self' https://www.youtube.com https://www.youtube-nocookie.com; img-src 'self' https://i.ytimg.com data:; style-src 'self' 'unsafe-inline'; media-src https://*.googlevideo.com"
