[build]
  publish = "public"
  functions = "netlify/functions"

# Members – tylko active/admin
[[redirects]]
  from = "/members/*"
  to = "/members/:splat"
  status = 200
  force = true
  conditions = { Role = ["active", "admin"] }

[[redirects]]
  from = "/members/*"
  to = "/dashboard.html"
  status = 302

# Dashboard – dostęp tylko dla zalogowanych (pending/active/admin)
[[redirects]]
  from = "/dashboard.html"
  to = "/dashboard.html"
  status = 200
  force = true
  conditions = { Role = ["pending", "active", "admin"] }

[[redirects]]
  from = "/dashboard.html"
  to = "/"
  status = 302

# Wymuś HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true
